default_platform :ios

platform :ios do
  

  desc "Creates new screenshots and uploads them to iTunes Connect"
  lane :screenshots do
    snapshot
    deliver(skip_metadata: true, force: true)
  end

  desc "Submits a new Beta Build to Apple TestFlight"
  lane :beta do
    archive
    pilot(
      ipa: "../bin/builds/FLSVertretungsplan.iOS.ipa",
      distribute_external: true,
      changelog: File.read('metadata/beta-release-notes.txt')
    )
  end

  desc "Deploys a new version to the App Store"
  lane :release do
    archive
    snapshot
    deliver(
      submit_for_review: true,
      automatic_release: false,
      ipa: "../bin/builds/FLSVertretungsplan.iOS.ipa",
      force: true
    )
  end

  def archive
    sh("msbuild ../FLSVertretungsplan.iOS.csproj /p:Configuration=Release /p:Platform=iPhone /p:IpaPackageDir=bin/builds /p:BuildIpa=true /t:Build")
  end

  def snapshot
    sh("msbuild ../../iOSUITests/iOSUITests.csproj")
    sh("nunit-console ../../iOSUITests/bin/Debug/iOSUITests.dll")
    frameit
  end
end