using System;
using System.Collections.ObjectModel;

namespace FLSVertretungsplan
{
    public static class DefaultData
    {
        public static Collection<string> Schools = new Collection<string> {
            "BFS",
            "BG",
            "BS",
            "HBFS",
            "InteA"
        };

        public static Collection<SchoolClass> SchoolClasses = new Collection<SchoolClass>
        {
            new SchoolClass("BFS", "1081"),
            new SchoolClass("BFS", "1082"),
            new SchoolClass("BFS", "1181"),
            new SchoolClass("BG", "11 REFILAS"),
            new SchoolClass("BG", "11/1 W"),
            new SchoolClass("BG", "11/2 W"),
            new SchoolClass("BG", "11/3 W"),
            new SchoolClass("BG", "11/4 W"),
            new SchoolClass("BG", "11/5 W/Bili"),
            new SchoolClass("BG", "11/6 DV"),
            new SchoolClass("BG", "11/7 DV"),
            new SchoolClass("BG", "11/8 CT"),
            new SchoolClass("BG", "11/9 G"),
            new SchoolClass("BG", "11/10 G"),
            new SchoolClass("BG", "11/11 G"),
            new SchoolClass("BG", "11/12 M"),
            new SchoolClass("BG", "11/13 ET"),
            new SchoolClass("BG", "12"),
            new SchoolClass("BG", "13"),
            new SchoolClass("BG", "SPORT11"),
            new SchoolClass("BG", "SPORT12"),
            new SchoolClass("BG", "SPORT13"),
            new SchoolClass("BS", "1021"),
            new SchoolClass("BS", "1022"),
            new SchoolClass("BS", "1023"),
            new SchoolClass("BS", "1031"),
            new SchoolClass("BS", "1035"),
            new SchoolClass("BS", "1036"),
            new SchoolClass("BS", "1037"),
            new SchoolClass("BS", "1038"),
            new SchoolClass("BS", "1039"),
            new SchoolClass("BS", "1041"),
            new SchoolClass("BS", "1042"),
            new SchoolClass("BS", "1045"),
            new SchoolClass("BS", "1051"),
            new SchoolClass("BS", "1061"),
            new SchoolClass("BS", "1062"),
            new SchoolClass("BS", "1063"),
            new SchoolClass("BS", "1071"),
            new SchoolClass("BS", "1075"),
            new SchoolClass("BS", "1076"),
            new SchoolClass("BS", "1081"),
            new SchoolClass("BS", "1082"),
            new SchoolClass("BS", "1121"),
            new SchoolClass("BS", "1122"),
            new SchoolClass("BS", "1123"),
            new SchoolClass("BS", "1124"),
            new SchoolClass("BS", "1131"),
            new SchoolClass("BS", "1136"),
            new SchoolClass("BS", "1137"),
            new SchoolClass("BS", "1138"),
            new SchoolClass("BS", "1139"),
            new SchoolClass("BS", "1141"),
            new SchoolClass("BS", "1142"),
            new SchoolClass("BS", "1145"),
            new SchoolClass("BS", "1151"),
            new SchoolClass("BS", "1161"),
            new SchoolClass("BS", "1162"),
            new SchoolClass("BS", "1163"),
            new SchoolClass("BS", "1171"),
            new SchoolClass("BS", "1175"),
            new SchoolClass("BS", "1176"),
            new SchoolClass("BS", "1181"),
            new SchoolClass("BS", "1221"),
            new SchoolClass("BS", "1222"),
            new SchoolClass("BS", "1223"),
            new SchoolClass("BS", "1225"),
            new SchoolClass("BS", "1231"),
            new SchoolClass("BS", "1241"),
            new SchoolClass("BS", "1242"),
            new SchoolClass("BS", "1245"),
            new SchoolClass("BS", "1251"),
            new SchoolClass("BS", "1261"),
            new SchoolClass("BS", "1262"),
            new SchoolClass("BS", "1271"),
            new SchoolClass("BS", "1275"),
            new SchoolClass("BS", "1276"),
            new SchoolClass("HBFS", "1191"),
            new SchoolClass("HBFS", "1192"),
            new SchoolClass("HBFS", "1193"),
            new SchoolClass("HBFS", "1291"),
            new SchoolClass("HBFS", "1292"),
            new SchoolClass("InteA", "InteA 1"),
            new SchoolClass("InteA", "InteA 2"),
            new SchoolClass("InteA", "InteA 3"),
            new SchoolClass("InteA", "InteA Sport")
        };
    }
}
